# ruff.toml
line-length = 120
indent-width = 4

[lint]
select = ["E", "F", "B", "I"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
